# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 20:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='profile',
            field=models.ForeignKey(help_text='Which user owns this car?', on_delete=django.db.models.deletion.CASCADE, related_name='car', to='track_n_drive.Profile'),
        ),
        migrations.AlterField(
            model_name='futurerepair',
            name='date_of_repair',
            field=models.DateField(default=datetime.date(2017, 11, 29), help_text='Enter a date for this repair'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='date_made',
            field=models.DateField(default=datetime.date(2017, 11, 29), help_text='Enter the date of repair'),
        ),
    ]
