# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-12 04:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futurerepair',
            name='date_of_repair',
            field=models.DateField(default=datetime.date(2017, 12, 11), help_text='Enter a date for this repair'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='date_made',
            field=models.DateField(default=datetime.date(2017, 12, 11), help_text='Enter the date of repair'),
        ),
    ]
