# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='technician',
        ),
        migrations.AlterField(
            model_name='car',
            name='registration',
            field=models.CharField(blank=True, help_text='Enter the registration of the car.', max_length=50, null=True),
        ),
    ]
