# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(help_text='Enter your ID.', max_length=30)),
                ('user', models.CharField(help_text='Enter your Name.', max_length=30)),
                ('address', models.EmailField(help_text='Enter your Email.', max_length=254)),
            ],
        ),
    ]
