# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0002_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateField(blank=True, null=True)),
                ('email', models.ForeignKey(help_text='Select a email.', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.Email')),
            ],
        ),
    ]
