# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 17:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0002_auto_20171030_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repair',
            name='date_made',
            field=models.DateField(default=datetime.date(2017, 10, 31)),
        ),
    ]
