# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 01:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0002_auto_20171031_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='car',
            field=models.ForeignKey(help_text='Car Insurance', null=True, on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.Car'),
        ),
    ]
