# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 01:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0003_insurance_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='user',
        ),
    ]
