# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0003_emailtimings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneTimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateField(blank=True, null=True)),
                ('unique_id', models.ForeignKey(help_text='Select a Phone.', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.Phone')),
            ],
        ),
    ]
