# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0004_remove_insurance_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtimings',
            old_name='notify',
            new_name='notification',
        ),
        migrations.RenameField(
            model_name='futurerepair',
            old_name='date_made',
            new_name='date_of_repair',
        ),
        migrations.RenameField(
            model_name='phonetimings',
            old_name='notify',
            new_name='notification',
        ),
    ]
