# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0004_phonetimings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_timings', models.ForeignKey(help_text='Select an email timing.', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.EmailTimings')),
                ('phone_timings', models.ForeignKey(help_text='Select a phone timing.', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.PhoneTimings')),
            ],
        ),
    ]
