# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0005_auto_20171031_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='futurerepair',
            old_name='notify',
            new_name='notification',
        ),
    ]
