# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0005_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Enter the make of the car.', max_length=50)),
                ('model', models.CharField(help_text='Enter the model of the car.', max_length=50)),
                ('year', models.IntegerField(help_text='Enter the year of the car.', max_length=10)),
                ('engine_type', models.CharField(help_text='Enter the engine type of the car.', max_length=50)),
                ('repairs', models.CharField(help_text='Enter the repair if any for the car', max_length=100)),
                ('mileage', models.IntegerField(help_text='Enter the mileage of the car', max_length=15)),
                ('oil_type', models.CharField(help_text='Enter the oil type of the car.', max_length=50)),
                ('color', models.CharField(help_text='Enter the color of the car.', max_length=50)),
                ('registration', models.CharField(help_text='Enter the registration of the car.', max_length=50)),
                ('vin_number', models.IntegerField(help_text='Enter the vin number of the car', max_length=50)),
            ],
        ),
    ]
