# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0006_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name for the repair.', max_length=200)),
                ('cost', models.IntegerField(help_text='Enter them cost for the repair', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TechAddedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_name', models.CharField(help_text='Information Category', max_length=200)),
                ('information_contents', models.CharField(help_text='Information to Add', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='Enter your first name.', max_length=30)),
                ('lname', models.CharField(help_text='Enter your last name.', max_length=30)),
                ('street', models.CharField(help_text='Enter the street adress of the technician.', max_length=100)),
                ('city', models.CharField(help_text='Enter the city of the technician.', max_length=100)),
                ('company', models.CharField(help_text='Enter the company of the technician.', max_length=100)),
                ('other_info', models.ManyToManyField(help_text='Additional Information', to='track_n_drive.TechAddedInfo')),
            ],
        ),
        migrations.AddField(
            model_name='repair',
            name='technician',
            field=models.ForeignKey(help_text='Select the technician for the repair', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.Technician'),
        ),
    ]
