# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0006_auto_20171031_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User Email', null=True, on_delete=django.db.models.deletion.SET_NULL, to='track_n_drive.User'),
        ),
        migrations.AlterField(
            model_name='futurerepair',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Select the technician for the repair', null=True, on_delete=django.db.models.deletion.SET_NULL, to='track_n_drive.Technician'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='car',
            field=models.ForeignKey(help_text='Car Insurance', null=True, on_delete=django.db.models.deletion.SET_NULL, to='track_n_drive.Car'),
        ),
        migrations.AlterField(
            model_name='license',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User License', null=True, on_delete=django.db.models.deletion.SET_NULL, to='track_n_drive.User'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User Phone', null=True, on_delete=django.db.models.deletion.SET_NULL, to='track_n_drive.User'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Select the technician for the repair', null=True, on_delete=django.db.models.deletion.SET_NULL, to='track_n_drive.Technician'),
        ),
        migrations.AlterField(
            model_name='techaddedinfo',
            name='tech',
            field=models.ForeignKey(blank=True, help_text='Technician', null=True, on_delete=django.db.models.deletion.SET_NULL, to='track_n_drive.Technician'),
        ),
        migrations.AlterField(
            model_name='useraddedinfo',
            name='user_info',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, to='track_n_drive.User'),
        ),
    ]
