# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0007_auto_20171031_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futurerepair',
            options={'ordering': ['date_of_repair']},
        ),
        migrations.AlterModelOptions(
            name='insurance',
            options={'ordering': ['expiration_date']},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['expiration_date']},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'ordering': ['date_made']},
        ),
        migrations.AlterField(
            model_name='futurerepair',
            name='car',
            field=models.ForeignKey(help_text='Select the car that was repaired', on_delete=django.db.models.deletion.CASCADE, related_name='futurerepair', to='track_n_drive.Car'),
        ),
        migrations.AlterField(
            model_name='futurerepair',
            name='date_of_repair',
            field=models.DateField(default=datetime.date(2017, 11, 1)),
        ),
        migrations.AlterField(
            model_name='repair',
            name='car',
            field=models.ForeignKey(help_text='Select the car that was repaired', on_delete=django.db.models.deletion.CASCADE, related_name='repair', to='track_n_drive.Car'),
        ),
        migrations.AlterField(
            model_name='repair',
            name='date_made',
            field=models.DateField(default=datetime.date(2017, 11, 1)),
        ),
        migrations.AlterField(
            model_name='useraddedinfo',
            name='user_info',
            field=models.ForeignKey(blank=True, help_text='User', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info', to='track_n_drive.User'),
        ),
    ]
