# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0007_auto_20171029_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddedInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information_name', models.CharField(help_text='Information Category', max_length=200)),
                ('information_contents', models.CharField(help_text='Information to Add', max_length=200)),
            ],
        ),
    ]
