# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0008_auto_20171101_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techaddedinfo',
            name='tech',
            field=models.ForeignKey(blank=True, help_text='Technician', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info', to='track_n_drive.Technician'),
        ),
    ]
