# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0008_useraddedinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('email_timings', models.ManyToManyField(help_text='When should you be notified?', to='track_n_drive.PhoneTimings')),
                ('phone_timings', models.ManyToManyField(help_text='When should you be notified?', to='track_n_drive.EmailTimings')),
                ('repair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.Repair')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.Technician')),
            ],
        ),
    ]
