# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0009_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_num', models.CharField(help_text='Enter your license number', max_length=50)),
                ('license_class', models.CharField(help_text='Enter your license class', max_length=50)),
                ('expiration_date', models.DateField()),
            ],
        ),
    ]
