# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-29 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('track_n_drive', '0010_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_num', models.CharField(help_text='Enter your insurance number', max_length=30)),
                ('company', models.CharField(help_text='Enter your company', max_length=30)),
                ('coverage', models.CharField(help_text='Enter your coverage', max_length=30)),
                ('expiration_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(help_text='Enter your first name.', max_length=30)),
                ('lname', models.CharField(help_text='Enter your last name.', max_length=30)),
                ('password', models.CharField(help_text='Enter your password.', max_length=30)),
                ('unique_id', models.CharField(help_text='Enter your ID.', max_length=30)),
                ('cars', models.ManyToManyField(help_text='Select a car for this User.', to='track_n_drive.Car')),
                ('insurance', models.ForeignKey(help_text='Select a insurance for this User.', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.Insurance')),
                ('license', models.ForeignKey(help_text='Select a license for this User.', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.License')),
                ('notifications', models.ForeignKey(help_text='Notifications for this User.', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.Notifications')),
                ('other_info', models.ForeignKey(help_text='Enter user info.', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.UserAddedInfo')),
                ('phone', models.ForeignKey(help_text='Select a phone for this User.', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.Phone')),
                ('settings', models.ForeignKey(help_text='Select a phone for this User.', on_delete=django.db.models.deletion.CASCADE, to='track_n_drive.Settings')),
                ('technician', models.ManyToManyField(help_text='Select a Technician for this User.', to='track_n_drive.Technician')),
            ],
        ),
    ]
